### ISSUE TITLE
Please pull my repo....

### ISSUE THREAD

**Issue by docwhat** [apotonick/rspec-apotomo#1]
Hello!

My name is Christian Höltje.  At work we're using your excellent Apotomo.  We also use RSpec for testing.  Therefore we decided to go ahead and write `rspec-apotomo` since it seems you would like one. :-)

I have a first version of `rspec-apotomo` ready for your to pull at https://github.com/docwhat/rspec-apotomo -- it is actually useful for writing tests (though we still have some more features to implement).

I would suggest that you pull my repo directly into your repo:

```
git clone git@github.com:apotonick/rspec-apotomo.git
cd rspec-apotomo
git pull git://github.com/docwhat/rspec-apotomo.git
git push
```

The above clones your repo, pulls our commits into it and then pushes it all up to your repo.

We still have some more work we plan on doing over the next couple weeks.  We can either submit them via Pull Requests or you could just give me ([docwhat](https://github.com/docwhat)) and Jake Goulding ([shepmaster](https://github.com/shepmaster)) developer rights on rspec-apotomo.

If you want to talk to me or Jake on Freenode IRC, we are `docwhat` and `shep-werk`. We'll be hanging around there for the next week or two while we work on rspec-apotomo.

Our TODO list at the moment:
- Add `assign()` support.
- Add the rails generators.
- Refactor some of the duplicate code out of `rspec-apotomo` and into `apotomo` (we'll submit pull requests for that).

Feel free to suggest any other TODO items.

Thanks again.

Ciao!

**Comment by apotonick** [comment]
Awesome work, guys. Thank you soooo much. I owe you some beers. Things we gotta fix are
- Generator
- Triggering/asserting events (see https://github.com/apotonick/rspec-apotomo/commit/bac7540c330ba29df19b683b594b50d8ceebec71)
- Some more docs.

Tried to add you as collaborators but Github wouldn't let me do it.

I will take care of extracting stuff to Apotomo::TestCase::TestMethods so we don't have redundancy in TestCase/RSpec code.

Are you ready?

**Comment by docwhat** [comment]
I'm in EDT (UTC - 4 hours).... so in about 10 hours I'll arrive at work and hop on IRC.  See you then!

**Comment by apotonick** [comment]
Haha ok, see you soon. Here is the refactoring of TestCase: https://github.com/apotonick/apotomo/commit/ca56e9060e87b982a05afa54ea3f3f37cd5c1296

So we need a new apotomo release.

BTW, I still can't run rake spec in rspec-apotomo. It simply does nothing.... Can you help?

**Comment by docwhat** [comment]
What is the next version? 1.1.3 or 1.2?  I want to get the version right in my dependencies....
